### ISSUE TITLE
Defintion of the function R_Z

### ISSUE THREAD

**Issue by VDelport** [jaishreedhage/JPEG-image-compression#1]
In the m-file encode.m  a function R_Z(R,zeroes) is used, but unfortunately there is no m-file where the function R_Z() is defined. Would you please commit the function R_Z() to your GitHub project? Thank you in advanced.

**Comment by jaishreedhage** [comment]
The file has been pushed. 
Thanks for bringing this to my notice.  :)
Let me know if there is any other issue.
